### ISSUE TITLE
Boston Housing Dataset cannot be downloaded from Kraggle

### ISSUE THREAD

**Issue by linhmai19** [learn-co-curriculum/dsc-project-eda-with-pandas#6]
I cannot download the Boston Housing Dataset from Kraggle. It said on Learn.co that I should follow the provided link and click on "Data" tab to download the dataset. However, as soon as I click on "Data" tab, it led me to a blank page. I could not download any dataset to complete the EDA with Pandas project in the Module 1 section 4 (2.1 Data Science version).

**Comment by hoffm386** [comment]
@linhmai19 I believe this was a short-term error on Kaggle's platform, rather than something we can control in our curriculum. You should be able to use the CSV files directly located in this repository to complete this lab, so I'm going to close out this issue
